Repository slatedb/slatedb, pull requests merged in 2024-09, with the labels that each got.

#175 Simplify BloomFilterBuilder.filter_bytes
  src/filter.rs
Labels: enhancement, size:XS

#171 make compactor tokio handle configurable
  src/compactor.rs
  src/config.rs
  src/db.rs
Labels: enhancement, size:S

#172 sst: compress bloom filters
  src/sst.rs
Labels: enhancement, size:M

#178 chore: add rustfmt.toml
  rustfmt.toml
  src/blob.rs
  src/block.rs
  src/block_iterator.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/compactor_state.rs
  src/config.rs
  src/db.rs
  src/db_bench/args.rs
  src/db_bench/db_bench.rs
  src/db_bench/main.rs
  src/db_common.rs
  src/db_state.rs
  src/filter.rs
  src/flatbuffer_types.rs
  src/flush.rs
  src/manifest.rs
  src/manifest_store.rs
  src/mem_table.rs
  src/mem_table_flush.rs
  src/merge_iterator.rs
  src/metrics.rs
  src/size_tiered_compaction.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
  src/transactional_object_store.rs
Labels: maintenance, size:L

#180 fix: use stable in rustfmt.toml
  rustfmt.toml
Labels: bug, size:XS

#181 Docs to rfcs
  rfcs/0001-manifest.md
  rfcs/0002-compaction.md
Labels: documentation, size:XS

#137 Feat/in memory block cache
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  src/block_iterator.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/compactor_state.rs
  src/config.rs
  src/db.rs
  src/db_state.rs
  src/inmemory_cache.rs
  src/lib.rs
  src/merge_iterator.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
Labels: size:XL

#184 Upgrade all dependencies
  Cargo.lock
  Cargo.toml
Labels: maintenance, size:S

#190 manifest: make fields required
  schemas/sst.fbs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
Labels: enhancement, size:M

#139 add a local-disk cache layer
  Cargo.lock
  Cargo.toml
  README.md
  src/cached_object_store.rs
  src/compactor.rs
  src/config.rs
  src/db.rs
  src/error.rs
  src/lib.rs
  src/metrics.rs
Labels: size:XXL

#202 Fix typos in compaction docs
  rfcs/0002-compaction.md
Labels: documentation, size:S

#205 Rename SSTableHandle to SsTableHandle
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/compactor_state.rs
  src/db.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/flush.rs
  src/size_tiered_compaction.rs
  src/sorted_run_iterator.rs
  src/sst_iter.rs
  src/tablestore.rs
Labels: size:L

#200 feat: add foyer as an in-memory option
  Cargo.lock
  Cargo.toml
  src/inmemory_cache.rs
Labels: enhancement, size:M

#209 Close `db` in `db-bench` tool to prevent `JoinError::Cancelled` messages
  src/db_bench/main.rs
Labels: bug, size:XS

#208 Add some steps to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, size:XS

#189 Add garbage collector
  Cargo.lock
  Cargo.toml
  README.md
  src/compactor.rs
  src/config.rs
  src/db.rs
  src/db_state.rs
  src/error.rs
  src/garbage_collector.rs
  src/lib.rs
  src/manifest_store.rs
  src/metrics.rs
  src/tablestore.rs
  src/transactional_object_store.rs
Labels: enhancement, size:XXL

#211 fix(cache): oom when enabled object store cache
  src/cached_object_store.rs
Labels: size:M

#212 first pass at slatedb read-manifest CLI
  .gitignore
  Cargo.lock
  Cargo.toml
  src/admin.rs
  src/cli/args.rs
  src/cli/main.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/lib.rs
  src/manifest.rs
Labels: enhancement, size:L

#217 Initial fizzbee model for the basic slatedb keyvalue store
  specs/README.md
  specs/kvstore/KeyValueStore.fizz
Labels: documentation, size:L

#219 Use `dotenvy` crate for all binaries
  Cargo.toml
Labels: enhancement, size:XS

#221 support list-manifests and read specific manifest for slatedb CLI
  src/admin.rs
  src/cli/args.rs
  src/cli/main.rs
  src/manifest_store.rs
Labels: enhancement, size:L

#222 Remove `SsTableInfoOwned` and add `SsTableInfo`
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/size_tiered_compaction.rs
  src/sst.rs
Labels: enhancement, size:L

#170 support configuring the filter bits per key
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/config.rs
  src/db.rs
  src/garbage_collector.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
Labels: enhancement, size:L

#223 feat(filter): implement hash sharing to reduce filter cost
  src/db.rs
  src/filter.rs
  src/sst.rs
Labels: enhancement, size:M

#216 cache indexes and bloom filters in memory
  rustfmt.toml
  src/inmemory_cache.rs
  src/sst_iter.rs
  src/tablestore.rs
Labels: enhancement, size:L

#220 Use ulid, no crash protection, single flush thread
  specs/kvstore/KeyValueStore.fizz
Labels: enhancement, size:M

#194 Eliminate all print, println, eprintln calls from the codebase
  Cargo.lock
  Cargo.toml
  src/compaction_execute_bench/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/db_bench/db_bench.rs
  src/db_bench/main.rs
  src/mem_table_flush.rs
Labels: enhancement, size:M

#233 S3 Benchmarking Tool
  Cargo.toml
  src/s3_bench/README.md
  src/s3_bench/main.rs
  src/s3_bench/run.sh
Labels: enhancement, size:XL

#234 refactor: Rename InMemoryCache to DbCache
  src/config.rs
  src/db.rs
  src/db_cache.rs
  src/lib.rs
  src/tablestore.rs
Labels: maintenance, size:M

#238 fix(bench): fix s3_bench can't find cache module
  src/s3_bench/main.rs
Labels: bug, size:S

#240 Adding missing dependencies to README
  README.md
Labels: documentation, size:XS

#231 feat(cache): Add option to provide a cache instance.
  Cargo.toml
  src/block.rs
  src/compactor.rs
  src/config.rs
  src/db.rs
  src/db_cache.rs
  src/db_cache/foyer.rs
  src/db_cache/moka.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/s3_bench/main.rs
  src/tablestore.rs
Labels: enhancement, size:XL

#242 fix(cache): Use the cached entries size as weights to calculate the size of the cache
  src/block.rs
  src/db_cache.rs
  src/db_cache/foyer.rs
  src/db_cache/moka.rs
  src/filter.rs
  src/flatbuffer_types.rs
  src/s3_bench/main.rs
  src/sst.rs
Labels: bug, size:L

#239 feat(block): support prefix key encoding
  src/block.rs
  src/block_iterator.rs
  src/sst_iter.rs
Labels: enhancement, size:M

#244 Use macros instead of if's for block cache config
  src/config.rs
Labels: enhancement, size:S
