Repository slatedb/slatedb, pull requests merged in 2024-12, with the labels that each got.

#362 chore: use mod.rs in db_cache
  src/db_cache/mod.rs
Labels: maintenance, size:XS

#355 GC should not delete manifests/ssts referenced by active checkpoints
  src/admin.rs
  src/checkpoint.rs
  src/garbage_collector.rs
  src/manifest.rs
  src/manifest_store.rs
Labels: bug, size:XXL

#377 Remove unused lifetimes and use div_ceil in object storage cache
  src/cached_object_store/object_store.rs
  src/cli/main.rs
  src/flatbuffer_types.rs
  src/mem_table.rs
  src/sst.rs
Labels: size:M

#372 Add a microbench bench test to detect performance regressions
  Cargo.lock
  Cargo.toml
  benches/db_operations.rs
Labels: enhancement, size:M

#376 Add ID to ManifestMissing error
  src/admin.rs
  src/checkpoint.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
  src/error.rs
  src/garbage_collector.rs
  src/manifest_store.rs
Labels: size:L

#333 RFC for MergeOperator.
  rfcs/0006-merge-operator.md
Labels: enhancement, size:L

#375 Improve memtable throughput by avoiding unnecssary SkipList search.
  src/mem_table.rs
Labels: enhancement, size:M

#367 refactor garbage collector into individual tasks
  src/garbage_collector.rs
Labels: maintenance, size:L

#379 Cleanup some of the dead code annotations.
  src/bytes.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_state.rs
  src/iter.rs
  src/lib.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
  src/types.rs
Labels: maintenance, size:L

#381 Add `cargo bench` PR check and `bencher`nightly
  .github/workflows/nightly.yaml
  .github/workflows/pr.yaml
  Cargo.toml
Labels: enhancement, size:M

#383 Add `benchmark-db.sh` to nightly and publish results to the website
  .github/workflows/nightly.yaml
  src/bencher/benchmark-db.sh
Labels: size:L

#384 Add environment variables for benchmark
  .github/workflows/nightly.yaml
Labels: enhancement, size:XS

#385 Create slatedb-lfs directory for benchmark
  .github/workflows/nightly.yaml
Labels: size:XS

#386 Use Buildjet runner for nightly `benchmark-db.sh` performance test
  .github/workflows/nightly.yaml
Labels: maintenance, size:XS

#387 Print system info for perf tests and move data out of `/tmp`
  .github/workflows/nightly.yaml
Labels: size:S

#388 Ditch Buildjet for Warpbuild
  .github/workflows/nightly.yaml
Labels: size:XS

#393 Add `--clean` option for `bencher`
  .github/workflows/nightly.yaml
  src/admin.rs
  src/bencher/README.md
  src/bencher/args.rs
  src/bencher/benchmark-db.sh
  src/bencher/main.rs
Labels: enhancement, size:L

#395 Disable custom benchmark caching
  .github/workflows/nightly.yaml
Labels: size:S

#397 Add nightly.yaml perf test docs
  src/bencher/README.md
Labels: documentation, size:XS

#392 MergeOperator RFC: Simplify the section around TTL handling and make …
  rfcs/0006-merge-operator.md
Labels: documentation, size:M

#399 Simplify test_utils::assert_iterator.
  src/db.rs
  src/merge_iterator.rs
  src/sst.rs
  src/tablestore.rs
  src/test_utils.rs
  src/types.rs
Labels: enhancement, size:L

#373 tighten up error handling to prevent writer clients from blocking indefinitely
  src/admin.rs
  src/batch_write.rs
  src/compactor.rs
  src/db.rs
  src/db_common.rs
  src/db_state.rs
  src/error.rs
  src/flush.rs
  src/garbage_collector.rs
  src/lib.rs
  src/mem_table.rs
  src/mem_table_flush.rs
  src/utils.rs
Labels: enhancement, size:XL

#401 Add microbenchmarks pprof job
  .github/workflows/nightly.yaml
  Cargo.lock
  Cargo.toml
  benches/db_operations.rs
Labels: size:M

#403 Remove pprof's using `-f` in nightly
  .github/workflows/nightly.yaml
Labels: documentation, size:XS

#402 doc: fixed minor typo in manifest rfc
  rfcs/0001-manifest.md
Labels: documentation, size:XS

#361 Add CLEAN_SLATE.md
  CLEAN_SLATE.md
Labels: documentation, size:M

#342 Implementation of range scans from RFC-0005
  Cargo.lock
  Cargo.toml
  rfcs/0005-range-queries.md
  src/block_iterator.rs
  src/bytes_range.rs
  src/config.rs
  src/db.rs
  src/db_iter.rs
  src/db_state.rs
  src/error.rs
  src/iter.rs
  src/lib.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/proptest_util.rs
  src/sorted_run_iterator.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
  src/types.rs
Labels: enhancement, size:XXL

#412 Add checksum to filter and index block
  src/sst.rs
Labels: enhancement, size:M

#414 Brand SlateDB as a member of Commonhaus
  README.md
Labels: documentation, size:S

#418 Use `Arc` instead of `Rc` in `replay_wal`
  src/db.rs
Labels: enhancement, size:S

#413 Add Commonhaus FUNDING.yml
  .github/FUNDING.yml
Labels: size:XS

#417 Add scan range usage to readme
  README.md
Labels: documentation, size:M

#421 Remove unnecessary allow dead_code annotation
  src/db_iter.rs
Labels: maintenance, size:XS

#419 Upgrade `object_store` to support `put_if_not_exists` on S3 without DynamoDB
  Cargo.lock
  Cargo.toml
  src/admin.rs
Labels: size:S, dependencies

#420 Fix flaky `test_should_recover_imm_from_wal_after_flush_error` test
  src/db.rs
Labels: bug, size:S

#410 Refactor Block Tests to Use Table-Driven Test Cases
  src/block.rs
  src/test_utils.rs
  testdata/snapshots/slatedb__block__tests__block_with_merge.snap
  testdata/snapshots/slatedb__block__tests__block_with_tombstone.snap
  testdata/snapshots/slatedb__block__tests__test_block.snap
Labels: maintenance, size:L
