Repository slatedb/slatedb, pull requests merged in 2024-10, with the labels that each got.

#246 Fix typo in GC naming
  src/config.rs
  src/garbage_collector.rs
Labels: bug, size:S

#245 Build without features
  .github/workflows/pr.yaml
  Cargo.toml
  src/admin.rs
  src/s3_bench/main.rs
  src/sst.rs
  src/tablestore.rs
Labels: size:M

#210 Fetch WALs in parallel on recovery
  src/db.rs
  src/db_state.rs
  src/sst_iter.rs
Labels: enhancement, size:M

#247 Combine s3_bench and db_bench
  Cargo.toml
  src/admin.rs
  src/bencher/README.md
  src/bencher/args.rs
  src/bencher/benchmark-db.sh
  src/bencher/db.rs
  src/bencher/main.rs
  src/db_bench/args.rs
  src/db_bench/db_bench.rs
  src/db_bench/main.rs
  src/db_bench/s3.rs
  src/lib.rs
  src/s3_bench/README.md
  src/s3_bench/main.rs
  src/s3_bench/run.sh
  src/test_utils.rs
Labels: enhancement, size:XXL

#228 add design for timestamps and ttl
  rfcs/0003-timestamps-and-ttl.md
Labels: documentation, size:L

#251 [1/N] RFC-3: introduce row_attributes into row format for tombstones
  Cargo.lock
  Cargo.toml
  src/block.rs
  src/block_iterator.rs
  src/db_state.rs
  src/error.rs
  src/flatbuffer_types.rs
  src/lib.rs
  src/row_codec.rs
  src/size_tiered_compaction.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
Labels: enhancement, size:XL

#255 Allow AWS session token for admin/testing
  src/admin.rs
  src/bencher/README.md
Labels: enhancement, size:S

#254 Add `LocalFileSystem` as an option for bencher and CLI
  src/admin.rs
Labels: enhancement, size:S

#256 Add AWS session token docs
  src/admin.rs
Labels: documentation, size:XS

#257 make dynamoDB optional for admin
  src/admin.rs
  src/cli/main.rs
Labels: enhancement, size:S

#259 Db.flush should await flush from background thread
  src/db.rs
  src/flush.rs
  src/mem_table_flush.rs
Labels: enhancement, size:M

#258 [2/N] RFC-3: persist row attributes in the SST
  schemas/sst.fbs
  src/block_iterator.rs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
  src/row_codec.rs
Labels: enhancement, size:L

#261 Move `compaction_execute_bench` into `bencher` tool
  Cargo.toml
  src/bencher/README.md
  src/bencher/args.rs
  src/bencher/main.rs
  src/compaction_execute_bench.rs
  src/compaction_execute_bench/README.md
  src/compaction_execute_bench/compaction_execute_bench.rs
Labels: enhancement, size:XL

#262 Remove `s3_bench`
  src/bencher/args.rs
  src/s3_bench/main.rs
Labels: maintenance, size:L

#264 Add `WriteBatch` and `write_batch` operations for atomic batch writes
  src/batch.rs
  src/batch_write.rs
  src/db.rs
  src/flush.rs
  src/lib.rs
  src/mem_table.rs
Labels: enhancement, size:XL

#270 feat(db): Allow loading DbOptions from a configuration file or environment variables
  Cargo.lock
  Cargo.toml
  src/bencher/README.md
  src/bencher/SlateDb.toml
  src/bencher/args.rs
  src/bencher/benchmark-db.sh
  src/bencher/main.rs
  src/config.rs
  src/error.rs
  src/size_tiered_compaction.rs
Labels: enhancement, size:XL

#276 Add flanneur to maintainers!
  MAINTAINERS.md
Labels: size:XS

#265 [3/N] RFC-3: add timestamps
  rfcs/0003-timestamps-and-ttl.md
  schemas/sst.fbs
  src/batch_write.rs
  src/block.rs
  src/block_iterator.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/config.rs
  src/db.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/flush.rs
  src/garbage_collector.rs
  src/generated/manifest_generated.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/row_codec.rs
  src/size_tiered_compaction.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
  src/types.rs
Labels: enhancement, size:XXL

#272 Add azure blob store to benchmark, add fixed set key generator
  Cargo.toml
  src/admin.rs
  src/bencher/README.md
  src/bencher/args.rs
  src/bencher/db.rs
Labels: enhancement, size:M

#271 Fix race condition in writer fencing that could result in two writers being open at the same time.
  src/db.rs
  src/tablestore.rs
Labels: bug, size:M

#275 add basic compaction metrics
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/metrics.rs
Labels: enhancement, size:M

#279 Include timestamp when loading tables for compaction bench
  src/compaction_execute_bench.rs
Labels: bug, size:S

#281 Display more verbose object store error message
  src/error.rs
Labels: enhancement, size:XS

#282 [4/N] RFC-3: add support for ttl expiry during compaction
  schemas/sst.fbs
  src/batch.rs
  src/batch_write.rs
  src/bencher/db.rs
  src/block.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/config.rs
  src/db.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/row_codec.rs
  src/sst.rs
  src/sst_iter.rs
  src/test_utils.rs
  src/types.rs
Labels: enhancement, size:XL

#289 Using debug logs for db internal operations
  src/db_state.rs
Labels: enhancement, size:S

#292 Close DB in bencher
  src/bencher/args.rs
  src/bencher/benchmark-db.sh
  src/bencher/main.rs
Labels: bug, size:S
