Repository slatedb/slatedb, pull requests merged in 2024-11, with the labels that each got.

#290 Unify write commit pipe
  src/batch_write.rs
  src/bencher/db.rs
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
Labels: enhancement, size:L

#297 Use SlateDB.toml in bencher
  src/bencher/benchmark-db.sh
Labels: enhancement, size:XS

#296 chore(db): Propagate errors to the client.
  src/batch_write.rs
  src/db.rs
  src/db_common.rs
  src/error.rs
  src/flush.rs
  src/mem_table_flush.rs
Labels: enhancement, size:M

#299 chore(db): Improve DB initialization and docs.
  README.md
  src/config.rs
  src/db.rs
  src/db_cache/foyer.rs
  src/db_cache/moka.rs
  src/lib.rs
  src/tablestore.rs
Labels: documentation, size:L

#278 RFC for supporting checkpoints/clones
  rfcs/0004-checkpoints.md
Labels: documentation, size:XL

#304 chore: Separate WAL and MemTable flushing mechanisms.
  src/db.rs
  src/db_common.rs
  src/error.rs
  src/flush.rs
  src/mem_table_flush.rs
Labels: maintenance, size:M

#295 refactor(cached_object_store): Move FsCacheStorage into a new module.
  src/cached_object_store.rs
  src/cached_object_store/fs_cache_storage.rs
  src/db.rs
Labels: maintenance, size:XXL

#306 Use fp_registry when we create it in tests
  src/db.rs
Labels: size:S

#303 Throttle WAL writes even if await_durable is false
  src/batch_write.rs
  src/compactor.rs
  src/config.rs
  src/db.rs
  src/db_common.rs
  src/flush.rs
  src/mem_table.rs
Labels: enhancement, size:L

#280 DRAFT: RFC for range queries
  rfcs/0005-range-queries.md
Labels: documentation, size:L

#320 Add docs warning that blocks are held in memory when get() returns
  src/db.rs
Labels: documentation, size:S

#324 Upgrade `object_store` crate to latest
  Cargo.lock
Labels: size:XS, dependencies

#325 persist clock ticks in manifest
  schemas/manifest.fbs
  src/batch_write.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/compactor_state.rs
  src/config.rs
  src/db.rs
  src/db_state.rs
  src/error.rs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
  src/size_tiered_compaction.rs
Labels: enhancement, size:L

#326 update checkpoints rfc based on feedback about destroyed_at_s
  rfcs/0004-checkpoints.md
Labels: documentation, size:M

#302 [1/N] checkpoints: api and manifest model for creating checkpoints
  Cargo.lock
  Cargo.toml
  rfcs/0004-checkpoints.md
  schemas/manifest.fbs
  src/checkpoint.rs
  src/config.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
  src/lib.rs
  src/manifest.rs
  src/manifest_store.rs
  src/size_tiered_compaction.rs
Labels: enhancement, size:XXL

#298 feat(snapshot): add seqence number to sst rows; remove SstRowFeature
  schemas/sst.fbs
  src/block.rs
  src/block_iterator.rs
  src/compaction_execute_bench.rs
  src/compactor_executor.rs
  src/db.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/flush.rs
  src/garbage_collector.rs
  src/generated/manifest_generated.rs
  src/iter.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/row_codec.rs
  src/size_tiered_compaction.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
  src/types.rs
Labels: enhancement, size:XXL

#329 [2/N] checkpoints: add CLI commands for managing checkpoints
  Cargo.lock
  Cargo.toml
  rfcs/0004-checkpoints.md
  src/admin.rs
  src/checkpoint.rs
  src/cli/args.rs
  src/cli/main.rs
  src/db_state.rs
  src/flatbuffer_types.rs
Labels: documentation, enhancement, size:L

#321 fix(flush): Handle background flush errors.
  src/db.rs
  src/db_common.rs
  src/error.rs
  src/flush.rs
  src/manifest_store.rs
  src/mem_table_flush.rs
  src/tablestore.rs
Labels: bug, size:L

#334 Add release.yaml and RELEASE.md
  .github/workflows/release.yaml
  RELEASE.md
Labels: documentation, enhancement, size:M

#338 Install cargo-edit in release
  .github/workflows/release.yaml
Labels: maintenance, size:XS

#339 chore: table driven the tests cases in key_codec.rs with more test cases
  Cargo.lock
  Cargo.toml
  src/row_codec.rs
  src/test_utils.rs
  testdata/snapshots/slatedb__row_codec__tests__empty key suffix.snap
  testdata/snapshots/slatedb__row_codec__tests__large sequence number.snap
  testdata/snapshots/slatedb__row_codec__tests__large value.snap
  testdata/snapshots/slatedb__row_codec__tests__long key suffix.snap
  testdata/snapshots/slatedb__row_codec__tests__normal row with expire_ts.snap
  testdata/snapshots/slatedb__row_codec__tests__normal row without expire_ts.snap
  testdata/snapshots/slatedb__row_codec__tests__row with both timestamps.snap
  testdata/snapshots/slatedb__row_codec__tests__row with only create_ts.snap
  testdata/snapshots/slatedb__row_codec__tests__tombstone row.snap
  testdata/snapshots/slatedb__row_codec__tests__unicode key suffix.snap
Labels: size:L

#344 log the db config on startup
  src/config.rs
  src/db.rs
Labels: enhancement, size:S

#351 chore(db): Make DbOptions Debugable and log on JSON encode failure.
  src/config.rs
  src/db.rs
Labels: enhancement, size:M

#343 support running GC from the admin CLI
  Cargo.lock
  Cargo.toml
  src/admin.rs
  src/cli/args.rs
  src/cli/main.rs
  src/config.rs
  src/garbage_collector.rs
Labels: enhancement, size:XL

#358 refactor interrupt handler in gc [MINOR]
  src/admin.rs
  src/garbage_collector.rs
Labels: maintenance, size:M

#354 update CI/CD to run clippy on tests [MINOR]
  .github/workflows/pr.yaml
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
Labels: maintenance, size:S

#359 Use cargo-nextest to run tests in CI
  .config/nextest.toml
  .github/workflows/pr.yaml
Labels: maintenance, size:XS

#345 Add a GOVERNANCE.md document
  GOVERNANCE.md
  MAINTAINERS.md
  RELEASE.md
Labels: documentation, size:M

#364 Prevent memtable size underflow.
  src/mem_table.rs
Labels: size:S
