Repository slatedb/slatedb, pull requests merged in 2025-08, with the labels that each got.

#701 feat(snapshot): add retention min seq to manifest
  schemas/manifest.fbs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db_state.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/generated/manifest_generated.rs
  slatedb/src/size_tiered_compaction.rs
Labels: enhancement, size:M

#712 Remove structured logging
  Cargo.lock
  Cargo.toml
  slatedb-bencher/Cargo.toml
  slatedb-bencher/src/db.rs
  slatedb-bencher/src/main.rs
  slatedb-bencher/src/system_monitor.rs
  slatedb-cli/Cargo.toml
  slatedb-cli/src/main.rs
  slatedb-dst/Cargo.toml
  slatedb-dst/src/dst.rs
  slatedb-dst/src/utils.rs
  slatedb-dst/tests/simulation.rs
  slatedb/Cargo.toml
  slatedb/src/batch_write.rs
  slatedb/src/cached_object_store/storage_fs.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_cache/mod.rs
  slatedb/src/db_reader.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/garbage_collector/compacted_gc.rs
  slatedb/src/garbage_collector/manifest_gc.rs
  slatedb/src/garbage_collector/wal_gc.rs
  slatedb/src/manifest/mod.rs
  slatedb/src/manifest/store.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/tablestore.rs
  slatedb/src/test_utils.rs
  slatedb/src/wal_buffer.rs
  slatedb/tests/db.rs
Labels: maintenance, size:L

#733 Add a nightly DST test
  .config/nextest.toml
  .github/workflows/nightly.yaml
  Cargo.lock
  Cargo.toml
  slatedb-dst/Cargo.toml
  slatedb-dst/README.md
  slatedb-dst/src/dst.rs
  slatedb-dst/src/lib.rs
  slatedb-dst/src/utils.rs
  slatedb-dst/tests/simulation.rs
Labels: enhancement, size:L

#735 Cap DST nightly at 90% CPU usage
  .github/workflows/nightly.yaml
  slatedb-dst/src/dst.rs
  slatedb-dst/tests/simulation.rs
Labels: maintenance, size:S

#738 Use LocalFileSystem for nightly DST
  .github/workflows/nightly.yaml
  slatedb-dst/README.md
  slatedb-dst/src/dst.rs
  slatedb-dst/src/utils.rs
  slatedb-dst/tests/simulation.rs
Labels: enhancement, size:M

#739 Back to warpbuild for DST nightly test
  .github/workflows/nightly.yaml
Labels: maintenance, size:XS

#731 New website using Astro Starlight.
  .github/workflows/pr.yaml
  .github/workflows/release-website.yaml
  .github/workflows/release.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
  examples/Cargo.toml
  examples/README.md
  examples/src/azure_blob_storage.rs
  examples/src/create_checkpoint.rs
  examples/src/delete_checkpoint.rs
  examples/src/full_example.rs
  examples/src/refresh_checkpoint.rs
  examples/src/s3_compatible.rs
  examples/src/simple_example.rs
  examples/src/tracing_subscriber.rs
  slatedb/examples/azure_blob_storage.rs
  slatedb/examples/create_checkpoint.rs
  slatedb/examples/delete_checkpoint.rs
  slatedb/examples/full_example.rs
  slatedb/examples/refresh_checkpoint.rs
  slatedb/examples/s3_compatible.rs
  slatedb/examples/simple_example.rs
  slatedb/examples/tracing_subscriber.rs
  website/.gitignore
  website/README.md
  website/astro.config.mjs
  website/package-lock.json
  website/package.json
  website/public/favicon.png
  website/public/img/architecture-compaction.png
  website/public/img/architecture-read.png
  website/public/img/architecture-write.png
  website/public/img/architecture.png
  website/public/img/favicon.ico
  website/public/img/logo-full.svg
  website/public/img/logo.svg
  website/public/img/slatedb-hero.riv
  website/public/img/slatedb-opengraph.jpg
  website/src/components/Card.astro
  website/src/components/Footer.astro
  website/src/components/Header.astro
  website/src/components/Hero.astro
  website/src/components/Icons.ts
  website/src/components/PageFrame.astro
  website/src/components/SocialIcons.astro
  website/src/components/ThemeProvider.astro
  website/src/content.config.ts
  website/src/content/docs/docs/architecture.md
  website/src/content/docs/docs/faq.md
  website/src/content/docs/docs/introduction.md
  website/src/content/docs/docs/operations/logging.mdx
  website/src/content/docs/docs/performance.md
  website/src/content/docs/docs/quickstart.mdx
  website/src/content/docs/docs/tutorials/abs.mdx
  website/src/content/docs/docs/tutorials/checkpoint.mdx
  website/src/content/docs/docs/tutorials/s3.mdx
  website/src/content/docs/index.mdx
  website/src/styles/custom.css
  website/tsconfig.json
Labels: enhancement, size:XL

#740 Update action versions to release the website.
  .github/workflows/release-website.yaml
Labels: maintenance, size:XS

#742 Fix documentation issue for garbage collection: "poll_interval" -> "interval"
  slatedb/src/config.rs
  website/src/content/docs/docs/architecture.md
Labels: documentation, size:S

#743 Hide the website's theme selector on mobile views.
  website/src/styles/custom.css
Labels: enhancement, size:XS

#745 Upload pprof files to pprof.me
  .github/workflows/nightly.yaml
Labels: enhancement, size:M

#748 Add y-axis label to `benchmark` nightly tests
  slatedb-bencher/benchmark-db.sh
Labels: size:S

#751 Use 1h instead of 24h for compacted gc
  slatedb-dst/src/utils.rs
Labels: enhancement, size:S

#755 Add FizzBee LLM instructions to `.github/instructions`
  .github/instructions/fizzbee.instructions.md
  specs/README.md
Labels: documentation, size:S

#752 Update performance docs on website
  website/src/content/docs/docs/performance.md
Labels: documentation, size:M

#757 Remove extra clone creating a DbIterator.
  slatedb/src/reader.rs
Labels: maintenance, size:XS

#758 Make put_probability random.
  slatedb-dst/src/dst.rs
Labels: enhancement, size:S

#760 Remove duplicated examples.
  slatedb/examples/azure_blob_storage.rs
  slatedb/examples/create_checkpoint.rs
  slatedb/examples/delete_checkpoint.rs
  slatedb/examples/full_example.rs
  slatedb/examples/refresh_checkpoint.rs
  slatedb/examples/s3_compatible.rs
  slatedb/examples/simple_example.rs
  slatedb/examples/tracing_subscriber.rs
Labels: maintenance, size:L

#763 fix(wal): ensure batch wal append in atomic
  slatedb/src/batch_write.rs
  slatedb/src/mem_table.rs
  slatedb/src/wal_buffer.rs
Labels: bug, size:M

#769 Improvements to the Python bidings.
  Cargo.lock
  slatedb-py/README.md
  slatedb-py/src/lib.rs
  slatedb-py/tests/conftest.py
  slatedb-py/tests/test_basic_operations.py
  slatedb-py/uv.lock
  slatedb/Cargo.toml
  slatedb/src/db.rs
  slatedb/src/error.rs
Labels: enhancement, size:L

#771 docs(website): add a link to docs.rs
  website/astro.config.mjs
  website/src/components/SocialIcons.astro
Labels: documentation, size:S

#768 fix(snapshot): not use `Option` on recent_snapshot_min_seq
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/db.rs
  slatedb/src/db_state.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/size_tiered_compaction.rs
  slatedb/src/transaction_manager.rs
Labels: bug, size:L

#764 feat(db_cache): divide in-memory cache into data block cache and meta cache
  slatedb-bencher/benchmark-db.sh
  slatedb-bencher/src/args.rs
  slatedb-bencher/src/main.rs
  slatedb/src/config.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_cache/foyer.rs
  slatedb/src/db_cache/foyer_hybrid.rs
  slatedb/src/db_cache/mod.rs
  slatedb/src/db_cache/moka.rs
  slatedb/src/tablestore.rs
Labels: enhancement, size:L

#780 Make "conflicting manifest" log debug
  slatedb/src/compactor.rs
  slatedb/src/mem_table_flush.rs
Labels: size:XS

#801 Add Dosu bot to README.md
  README.md
Labels: documentation, size:XS

#802 Tweak URL for SlateDB Dosu bot
  README.md
Labels: size:XS

#803 Adjust nightly perf charts more
  slatedb-bencher/benchmark-db.sh
Labels: enhancement, size:M

#747 Warmup for disk cache and write through for put
  slatedb/src/cached_object_store/object_store.rs
  slatedb/src/config.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
Labels: enhancement, size:XL

#821 Add SQLync to README.md adopters
  README.md
Labels: documentation, size:XS

#822 Set `RUST_LOG` to info for nightly benchmark
  .github/workflows/nightly.yaml
Labels: size:XS

#824 Fix DST formatting to make build pass
  slatedb-dst/src/utils.rs
Labels: bug, size:XS

#805 feat(txn): Add conflict check for SI transaction
  slatedb/src/batch.rs
  slatedb/src/batch_write.rs
  slatedb/src/db_snapshot.rs
  slatedb/src/error.rs
  slatedb/src/transaction_manager.rs
Labels: enhancement, size:XXL

#826 Update funding model to custom Open Collective link
  .github/FUNDING.yml
Labels: size:XS

#827 Add OpenCollective badge to README
  README.md
Labels: size:XS

#829 [Minor]Fix example in the compaction RFC
  rfcs/0002-compaction.md
Labels: documentation, size:XS

#834 Make paths in RTD yaml file absolute
  slatedb-py/.readthedocs.yaml
Labels: documentation, size:XS

#835 Add go mod info for pkg.go.dev
  website/astro.config.mjs
Labels: documentation, size:XS

#837 Add Go tests to bindings-go in pr.yaml
  .github/workflows/pr.yaml
  website/astro.config.mjs
Labels: maintenance, size:M

#838 Add dedicated astro page for slatedb-go package
  website/astro.config.mjs
  website/src/pages/slatedb-go.astro
Labels: size:S

#839 Fix go import
  website/src/pages/slatedb-go.astro
Labels: size:XS

#842 Add Go module tag to release process
  .github/workflows/release-website.yaml
  .github/workflows/release.yaml
  website/src/pages/slatedb-go.astro
Labels: enhancement, size:S

#819 Retry sst put requests on Timeout.
  Cargo.lock
  Cargo.toml
  slatedb/Cargo.toml
  slatedb/src/manifest/store.rs
  slatedb/src/tablestore.rs
  slatedb/src/utils.rs
Labels: enhancement, size:M

#843 Add retry tests for manifest/WAL writes
  slatedb/src/manifest/store.rs
  slatedb/src/tablestore.rs
  slatedb/src/test_utils.rs
  slatedb/src/wal_buffer.rs
Labels: maintenance, size:L

#845 Refactor website
  examples/README.md
  rfcs/0007-api-errors.md
  website/.gitignore
  website/astro.config.mjs
  website/package-lock.json
  website/package.json
  website/public/img/architecture-compaction.png
  website/public/img/architecture-read.png
  website/public/img/architecture-write.png
  website/public/img/architecture.png
  website/scripts/generate-rfcs.js
  website/src/components/SocialIcons.astro
  website/src/content/docs/docs/architecture.md
  website/src/content/docs/docs/design/caching.mdx
  website/src/content/docs/docs/design/checkpoints.mdx
  website/src/content/docs/docs/design/clones.mdx
  website/src/content/docs/docs/design/compaction.mdx
  website/src/content/docs/docs/design/compression.mdx
  website/src/content/docs/docs/design/consistency.mdx
  website/src/content/docs/docs/design/files.mdx
  website/src/content/docs/docs/design/gc.mdx
  website/src/content/docs/docs/design/overview.mdx
  website/src/content/docs/docs/design/reads.mdx
  website/src/content/docs/docs/design/time.mdx
  website/src/content/docs/docs/design/writes.mdx
  website/src/content/docs/docs/get-started/faq.mdx
  website/src/content/docs/docs/get-started/introduction.mdx
  website/src/content/docs/docs/get-started/quickstart.mdx
  website/src/content/docs/docs/operations/benchmarks.mdx
  website/src/content/docs/docs/operations/cli.mdx
  website/src/content/docs/docs/operations/compatibility.mdx
  website/src/content/docs/docs/operations/configuration.mdx
  website/src/content/docs/docs/operations/errors.mdx
  website/src/content/docs/docs/operations/metrics.mdx
  website/src/content/docs/docs/operations/tuning.mdx
  website/src/content/docs/index.mdx
  website/src/content/docs/rfcs/.keep
Labels: documentation, size:XL

#848 Include README.md in the pypi packge
  slatedb-py/pyproject.toml
Labels: documentation, size:XS

#847 Set github action bot name and email
  .github/workflows/release.yaml
Labels: bug, size:XS
