Repository slatedb/slatedb, pull requests merged in 2025-07, with the labels that each got.

#654 fix: upgrade foyer to fix recovery
  Cargo.lock
  slatedb/Cargo.toml
Labels: size:XS, dependencies

#662 Migrate to workspace dependencies
  Cargo.toml
  slatedb-bencher/Cargo.toml
  slatedb-cli/Cargo.toml
  slatedb-py/Cargo.toml
  slatedb/Cargo.toml
Labels: size:L, dependencies

#666 Add compactor progress
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/wal_buffer.rs
Labels: enhancement, size:L

#668 Update nightly bencher tests to use Tigris instead of local disk
  .github/workflows/nightly.yaml
  Cargo.lock
  Cargo.toml
  slatedb-bencher/Cargo.toml
  slatedb-bencher/README.md
  slatedb-bencher/SlateDb.toml
  slatedb-bencher/benchmark-db.sh
  slatedb-bencher/src/args.rs
  slatedb-bencher/src/db.rs
  slatedb-bencher/src/main.rs
  slatedb-bencher/src/system_monitor.rs
  slatedb/src/db.rs
  slatedb/src/wal_buffer.rs
Labels: maintenance, size:L

#639 Support OpenDAL object stores
  Cargo.lock
  Cargo.toml
  slatedb/Cargo.toml
  slatedb/src/admin.rs
Labels: enhancement, size:M

#670 Add infrastructure sponsors to README.md
  README.md
Labels: documentation, size:XS

#658 Update RELEASE.md with Python binding instructions
  .github/workflows/python.yaml
  RELEASE.md
Labels: documentation, size:M

#672 Add some project ideas
  CONTRIBUTING.md
  README.md
Labels: documentation, size:S

#674 feat: add scan iterator functionality to PySlateDB and PySlateDBReader
  slatedb-py/src/lib.rs
  slatedb-py/tests/test_basic_operations.py
Labels: enhancement, size:L

#682 Record bytes_compacted correctly.
  .github/workflows/pr.yaml
  slatedb/src/compactor_executor.rs
Labels: bug, size:XS

#683 Remove tokio::time usage
  slatedb/Cargo.toml
  slatedb/clippy.toml
  slatedb/src/batch_write.rs
  slatedb/src/cached_object_store/storage_fs.rs
  slatedb/src/clock.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_cache/mod.rs
  slatedb/src/db_reader.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/garbage_collector/compacted_gc.rs
  slatedb/src/garbage_collector/manifest_gc.rs
  slatedb/src/garbage_collector/wal_gc.rs
  slatedb/src/manifest/store.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/retention_iterator.rs
  slatedb/src/tablestore.rs
  slatedb/src/utils.rs
  slatedb/src/wal_buffer.rs
Labels: enhancement, size:XL

#690 chore: add DbRead trait
  slatedb/src/db.rs
  slatedb/src/db_read.rs
  slatedb/src/db_reader.rs
  slatedb/src/lib.rs
  slatedb/src/reader.rs
Labels: maintenance, size:L

#697 Implement the Public Error API.
  Cargo.lock
  Cargo.toml
  rfcs/0007-api-errors.md
  slatedb-bencher/src/args.rs
  slatedb-py/src/lib.rs
  slatedb/Cargo.toml
  slatedb/src/admin.rs
  slatedb/src/batch.rs
  slatedb/src/checkpoint.rs
  slatedb/src/clock.rs
  slatedb/src/clone.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/config.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_cache/foyer.rs
  slatedb/src/db_cache/foyer_hybrid.rs
  slatedb/src/db_cache/mod.rs
  slatedb/src/db_cache/moka.rs
  slatedb/src/db_cache/serde.rs
  slatedb/src/db_iter.rs
  slatedb/src/db_read.rs
  slatedb/src/db_reader.rs
  slatedb/src/error.rs
  slatedb/src/filter_iterator.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/garbage_collector/compacted_gc.rs
  slatedb/src/garbage_collector/manifest_gc.rs
  slatedb/src/garbage_collector/wal_gc.rs
  slatedb/src/lib.rs
  slatedb/src/manifest/store.rs
  slatedb/src/reader.rs
  slatedb/src/sst_iter.rs
  slatedb/src/test_utils.rs
  slatedb/src/utils.rs
  slatedb/src/wal_buffer.rs
  slatedb/src/wal_replay.rs
Labels: documentation, enhancement, size:XXL

#698 Merge SettingsError into SlateDBError.
  slatedb/src/config.rs
  slatedb/src/error.rs
  slatedb/src/utils.rs
Labels: documentation, maintenance, size:M

#676 fix: Use finished blocks length to calculate the sst current size.
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/config.rs
  slatedb/src/db.rs
  slatedb/src/sorted_run_iterator.rs
  slatedb/src/sst.rs
  slatedb/src/sst_iter.rs
  slatedb/src/stats.rs
  slatedb/src/tablestore.rs
Labels: bug, size:L

#700 Add `gen_ulid` clock param
  slatedb/src/compactor_executor.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/utils.rs
Labels: enhancement, size:M

#694 Add deterministic simulation tests to SlateDB
  .config/nextest.toml
  .github/workflows/pr.yaml
  Cargo.lock
  Cargo.toml
  README.md
  slatedb-dst/Cargo.toml
  slatedb-dst/README.md
  slatedb-dst/src/dst.rs
  slatedb-dst/src/lib.rs
  slatedb-dst/src/utils.rs
  slatedb-dst/tests/simulation.rs
  slatedb/Cargo.toml
  slatedb/clippy.toml
  slatedb/src/batch.rs
  slatedb/src/clock.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/config.rs
  slatedb/src/lib.rs
  slatedb/src/rand.rs
  slatedb/src/test_utils.rs
Labels: enhancement, size:XXL

#708 Prevent ticker starvation
  slatedb/src/clock.rs
  slatedb/src/db.rs
Labels: bug, size:M
