Repository slatedb/slatedb, pull requests merged in 2025-04, with the labels that each got.

#531 More accurate SST size estimation for the memtable
  src/block.rs
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
  src/db_common.rs
  src/filter.rs
  src/mem_table.rs
  src/row_codec.rs
  src/sst.rs
  src/tablestore.rs
  src/wal_replay.rs
Labels: question, size:L

#538 make StoreProvider Send+Sync
  src/store_provider.rs
Labels: enhancement, size:XS

#539 chore: wrap async-trait to KeyValueIterator & SeekToKey
  src/block_iterator.rs
  src/filter_iterator.rs
  src/iter.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/merge_operator.rs
  src/sorted_run_iterator.rs
  src/sst_iter.rs
  src/test_utils.rs
Labels: enhancement, size:M

#537 refactor(reader.rs): add a LevelGet struct that filter max_seq in get() and tests with expire_ts handling
  src/db.rs
  src/db_reader.rs
  src/filter_iterator.rs
  src/mem_table.rs
  src/reader.rs
Labels: maintenance, size:XL

#547 chore: fix clippy; add rust-toolchain.toml
  rust-toolchain.toml
  src/bencher/main.rs
  src/cached_object_store/storage_fs.rs
  src/clone.rs
  src/db.rs
  src/error.rs
  src/filter.rs
  src/lib.rs
  src/tablestore.rs
Labels: maintenance, size:S

#543 delete VecDequeIterator
  Cargo.lock
  Cargo.toml
  src/db_iter.rs
  src/mem_table.rs
  src/reader.rs
Labels: enhancement, size:L

#546 refactor: let MergeIterator accepts Box<dyn KeyValueIterator>; merge SeekToKey into KeyValueIterator
  src/block_iterator.rs
  src/compactor_executor.rs
  src/db_iter.rs
  src/error.rs
  src/filter_iterator.rs
  src/iter.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/merge_operator.rs
  src/sorted_run_iterator.rs
  src/sst_iter.rs
  src/test_utils.rs
Labels: maintenance, size:L

#551 [hotfix] Avoid double-pinning of LevelGet getters.
  src/reader.rs
Labels: size:XS

#553 fix: fix build error when using dbiterator behind a Box<dyn>
  src/db.rs
  src/reader.rs
Labels: bug, size:M

#548 [bug] db_options.flush_interval=None broken
  src/db.rs
  src/flush.rs
Labels: bug, size:M

#307 fix(compaction): filter tombstones out when compacting into the last sorted run
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/types.rs
Labels: enhancement, size:L
