Repository slatedb/slatedb, pull requests merged in 2025-05, with the labels that each got.

#561 Verify that compression works without panics
  src/db.rs
Labels: bug, size:M

#562 chore: Remove duplicate references
  src/db.rs
Labels: maintenance, size:XS

#536 refactor(snapshot): add max_seq in scan
  src/db.rs
  src/db_iter.rs
  src/db_reader.rs
  src/reader.rs
Labels: enhancement, size:L

#563 chore: Fix typo
  src/mem_table.rs
Labels: size:XS

#559 RFC: Settings vs components
  rfcs/0010-settings-vs-components.md
Labels: documentation, size:M

#565 chore: add comment about last_wal_id and wal_id_last_compacted
  schemas/manifest.fbs
  src/mem_table.rs
Labels: documentation, size:XS

#568 chore: Add memtable track last_seq test
  src/mem_table.rs
Labels: maintenance, size:M

#533 Separate WAL RFC
  rfcs/0009-separate-wal.md
Labels: documentation, size:L

#570 Retry writer/compactor epoch bump on ManifestVersionExists errors
  src/manifest/store.rs
Labels: bug, size:M

#572 Make shutdown manifest conflict logs less scary
  src/compactor.rs
  src/mem_table_flush.rs
Labels: enhancement, size:XS

#575 Decompress block bytes before decoding
  slatedb/src/db.rs
  slatedb/src/sst.rs
Labels: bug, size:L

#569 refactor(wal): skip entries with seq that lower than last_l0_seq on replaying
  schemas/manifest.fbs
  slatedb/src/clone.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_reader.rs
  slatedb/src/db_state.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/generated/manifest_generated.rs
  slatedb/src/manifest/mod.rs
  slatedb/src/mem_table.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/size_tiered_compaction.rs
  slatedb/src/wal_replay.rs
Labels: size:L

#578 Fixing nightly perf tests
  .github/workflows/nightly.yaml
Labels: bug, size:XS

#580 chore(deps): upgrade foyer to v0.17.2
  Cargo.lock
  slatedb/Cargo.toml
Labels: size:XS, dependencies

#558 Initial support for separate WAL object store
  schemas/manifest.fbs
  slatedb/src/admin.rs
  slatedb/src/checkpoint.rs
  slatedb/src/clone.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_reader.rs
  slatedb/src/db_state.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/generated/manifest_generated.rs
  slatedb/src/lib.rs
  slatedb/src/manifest/store.rs
  slatedb/src/object_stores.rs
  slatedb/src/reader.rs
  slatedb/src/size_tiered_compaction.rs
  slatedb/src/sorted_run_iterator.rs
  slatedb/src/sst.rs
  slatedb/src/sst_iter.rs
  slatedb/src/store_provider.rs
  slatedb/src/tablestore.rs
  slatedb/src/wal_replay.rs
Labels: enhancement, size:XL

#581 doc: fix contributing guide nextest script
  CONTRIBUTING.md
Labels: documentation, size:XS

#579 fix(gc): Reimplement the garbage collector without crossbeam.
  Cargo.lock
  slatedb-cli/Cargo.toml
  slatedb-cli/src/main.rs
  slatedb/Cargo.toml
  slatedb/src/admin.rs
  slatedb/src/config.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/garbage_collector/compacted_gc.rs
  slatedb/src/garbage_collector/manifest_gc.rs
  slatedb/src/garbage_collector/stats.rs
  slatedb/src/garbage_collector/wal_gc.rs
Labels: bug, size:XXL

#583 fix(gc): Check the cancellation token before starting any gc tasks.
  slatedb/src/garbage_collector.rs
Labels: bug, size:M

#584 fix(foyer): bump to foyer v0.17.3 to fix recovery
  Cargo.lock
  slatedb/Cargo.toml
Labels: size:XS, dependencies

#585 Centralize RNG logic and add deterministic seeding support
  Cargo.lock
  slatedb/Cargo.toml
  slatedb/src/cached_object_store/storage_fs.rs
  slatedb/src/checkpoint.rs
  slatedb/src/clone.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_reader.rs
  slatedb/src/db_state.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/lib.rs
  slatedb/src/manifest/mod.rs
  slatedb/src/manifest/store.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/object_stores.rs
  slatedb/src/rand.rs
  slatedb/src/size_tiered_compaction.rs
  slatedb/src/sorted_run_iterator.rs
  slatedb/src/tablestore.rs
  slatedb/src/utils.rs
Labels: enhancement, size:L

#587 Add Clippy checks for rand RNGs
  slatedb/clippy.toml
  slatedb/src/cached_object_store/object_store.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/comparable_range.rs
  slatedb/src/lib.rs
  slatedb/src/proptest_util.rs
  slatedb/src/rand.rs
  slatedb/src/test_utils.rs
  slatedb/tests/db.rs
Labels: maintenance, size:M
