Repository slatedb/slatedb, pull requests merged in 2025-06, with the labels that each got.

#582 support patch releases after main has advanced
  .github/workflows/release.yaml
  RELEASE.md
Labels: enhancement, size:XS

#598 fix docstrings about manifest poll interval
  slatedb/src/config.rs
Labels: documentation, size:S

#599 Fix race condition in compaction executor
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
Labels: bug, size:M

#603 Use `SystemClock` instead of `std::time`
  slatedb-cli/src/main.rs
  slatedb/clippy.toml
  slatedb/src/admin.rs
  slatedb/src/cached_object_store/object_store.rs
  slatedb/src/cached_object_store/storage_fs.rs
  slatedb/src/checkpoint.rs
  slatedb/src/clock.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_cache/mod.rs
  slatedb/src/db_cache/moka.rs
  slatedb/src/db_reader.rs
  slatedb/src/db_state.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/manifest/store.rs
  slatedb/src/reader.rs
  slatedb/src/test_utils.rs
  slatedb/src/utils.rs
Labels: enhancement, size:L

#545 Add binary search to SstIterator::seek
  slatedb/src/sst_iter.rs
Labels: enhancement, size:L

#608 Clean up SST file if writer is fenced
  slatedb/src/db.rs
  slatedb/src/mem_table_flush.rs
Labels: enhancement, size:M

#614 Fix `test_memtable_flush_cleanup_when_fenced` so it doesn't fail
  slatedb/src/db.rs
Labels: bug, size:S

#616 Move GC tokio_handle to start_in_bg_thread
  slatedb/src/db/builder.rs
  slatedb/src/garbage_collector.rs
Labels: enhancement, size:S

#619 disable the db compactor for the compactor state tests
  slatedb/src/compactor_state.rs
Labels: size:XS

#519 feat(wal): add a wal buffer manager; support dirty read semantics in RFC-008
  slatedb/src/batch_write.rs
  slatedb/src/checkpoint.rs
  slatedb/src/compactor.rs
  slatedb/src/config.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_common.rs
  slatedb/src/db_reader.rs
  slatedb/src/db_state.rs
  slatedb/src/error.rs
  slatedb/src/flush.rs
  slatedb/src/lib.rs
  slatedb/src/mem_table.rs
  slatedb/src/oracle.rs
  slatedb/src/reader.rs
  slatedb/src/utils.rs
  slatedb/src/wal_buffer.rs
  slatedb/src/wal_id.rs
Labels: enhancement, size:XXL

#620 Add `CompactorBuilder` and make `Compactor` async
  slatedb/src/admin.rs
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/size_tiered_compaction.rs
  slatedb/src/test_utils.rs
Labels: enhancement, size:XL

#631 fix(wal): track db fatal when wal flusher got unrecoverable error
  slatedb/src/db.rs
  slatedb/src/wal_buffer.rs
Labels: bug, size:S

#627 Add more functions to the Python binding
  .gitignore
  slatedb-py/python/slatedb/slatedb.pyi
  slatedb-py/src/lib.rs
  slatedb-py/tests/test_basic_operations.py
Labels: enhancement, size:L

#642 Add SlateDBReader and SlateDBAdmin classes to Python bindings
  Cargo.lock
  slatedb-py/Cargo.toml
  slatedb-py/python/slatedb/slatedb.pyi
  slatedb-py/src/lib.rs
  slatedb-py/tests/conftest.py
  slatedb-py/tests/test_db_reader_operations.py
Labels: enhancement, size:L

#641 Insulate compactor from executor async runtimes
  slatedb/src/compactor.rs
  slatedb/src/error.rs
Labels: bug, size:M

#632 Remove `GarbageCollector::start_in_bg_thread`
  slatedb/clippy.toml
  slatedb/src/admin.rs
  slatedb/src/compactor.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/utils.rs
Labels: enhancement, size:L

#644 Disable cache for WAL replay iterator
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
Labels: enhancement, size:S

#652 test: let test_get_after_put to use explicit options instead of defaults
  slatedb/src/db.rs
Labels: size:S

#655 Default to Foyer cache and 256MiB `max_sst_size`
  slatedb/Cargo.toml
  slatedb/src/config.rs
  slatedb/src/tablestore.rs
Labels: enhancement, size:XS

#656 Replace broken toml-editor action with sed
  .github/workflows/release.yaml
Labels: size:XS
