Repository slatedb/slatedb, pull requests merged in 2025-02, with the labels that each got.

#465 Some building blocks for reverse scan
  src/block_iterator.rs
  src/clone.rs
  src/db.rs
  src/iter.rs
  src/mem_table.rs
  src/proptest_util.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
Labels: enhancement, size:L

#478 Fix flatbuffer formatting.
  schemas/manifest.fbs
Labels: size:S

#479 Relax signature of admin::create_checkpoint.
  src/admin.rs
  src/checkpoint.rs
  src/cli/main.rs
Labels: enhancement, size:L

#480 add clock synchronization mechanism
  src/batch_write.rs
  src/utils.rs
Labels: enhancement, size:M

#484 Use `u64` for SST metadata offset to support big SSTs
  src/blob.rs
  src/sst.rs
  src/tablestore.rs
Labels: enhancement, size:M

#482 support more dynamic creation/read of statistics
  src/admin.rs
  src/cached_object_store/mod.rs
  src/cached_object_store/object_store.rs
  src/cached_object_store/stats.rs
  src/cached_object_store/storage_fs.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/db.rs
  src/db_stats.rs
  src/garbage_collector.rs
  src/lib.rs
  src/metrics.rs
  src/stats.rs
Labels: enhancement, size:XL

#488 fix the object store cache metric prefix
  src/cached_object_store/stats.rs
Labels: bug, size:XS

#486 fix: cleanup compaction job on failure
  src/batch_write.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/compactor_state.rs
  src/db.rs
  src/flush.rs
  src/garbage_collector.rs
  src/mem_table_flush.rs
  src/utils.rs
Labels: bug, size:XL

#487 fix: leave behind a checkpoint when writing manifest from compactor
  src/compactor.rs
  src/manifest_store.rs
Labels: bug, size:L

#490 add bloom filter pos/neg/false pos stats
  src/db.rs
  src/db_stats.rs
Labels: enhancement, size:M

#491 add stats about block cache hits/misses and usage
  src/bytes_generator.rs
  src/db.rs
  src/db_cache/foyer.rs
  src/db_cache/mod.rs
  src/db_cache/moka.rs
  src/lib.rs
  src/sst.rs
  src/tablestore.rs
  src/test_utils.rs
Labels: enhancement, size:L

#492 fix: clamp the buffers backing entries inserted to the block cache
  src/block.rs
  src/db_cache/mod.rs
  src/filter.rs
  src/flatbuffer_types.rs
  src/utils.rs
Labels: bug, size:L

#458 Filter out expired records on retrieval
  src/config.rs
  src/db.rs
  src/filter_iterator.rs
  src/flush.rs
  src/lib.rs
  src/merge_iterator.rs
  src/test_utils.rs
  src/utils.rs
Labels: enhancement, size:XL
