Repository slatedb/slatedb, pull requests merged in 2025-10, with the labels that each got.

#926 [Minor]Refactor compaction validation to scheduler; replace SlateDBError in trait API
  slatedb/src/compactor.rs
  slatedb/src/compactor_state.rs
  slatedb/src/size_tiered_compaction.rs
Labels: enhancement, size:L

#927 docs: add example and documentation for GCS support
  Cargo.lock
  examples/Cargo.toml
  examples/README.md
  examples/src/google_cloud_storage.rs
  website/astro.config.mjs
  website/src/content/docs/docs/tutorials/abs.mdx
  website/src/content/docs/docs/tutorials/gcs.mdx
  website/src/content/docs/docs/tutorials/s3.mdx
Labels: documentation, size:L

#931 Improve object_store test_save_result_not_aligned
  slatedb/src/cached_object_store/object_store.rs
Labels: bug, size:XS
