Repository slatedb/slatedb, pull requests merged in 2025-09, with the labels that each got.

#695 Compaction persistence rfc
  rfcs/0012-compaction-state-persistence.md
  schemas/compactor.fbs
Labels: documentation, size:XL

#855 Add memtable flush logs
  slatedb/src/mem_table_flush.rs
Labels: enhancement, size:S

#811 add RFC-0012 for sequence tracking
  rfcs/0012-sequence-tracker.md
Labels: documentation, size:L

#860 Use .min() when determining min_compaction_sources in DST
  slatedb-dst/src/utils.rs
Labels: bug, size:XS

#830 Add validation for submitted compactions
  slatedb/src/compactor_state.rs
Labels: enhancement, size:L

#858 Invert `ObjectStore` retry logic
  slatedb/src/db_cache/foyer_hybrid.rs
  slatedb/src/db_cache/mod.rs
  slatedb/src/manifest/store.rs
  slatedb/src/tablestore.rs
  slatedb/src/utils.rs
Labels: enhancement, size:M

#849 Use `MessageDispatcher` to manage `GarbageCollector`
  slatedb/src/admin.rs
  slatedb/src/db/builder.rs
  slatedb/src/db_state.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/garbage_collector/compacted_gc.rs
  slatedb/src/garbage_collector/manifest_gc.rs
  slatedb/src/garbage_collector/wal_gc.rs
Labels: maintenance, size:L

#864 modify seq_tracker implementation to match RFC-12
  slatedb/src/seq_tracker.rs
Labels: enhancement, size:XL

#869 Wrap object stores in `RetryingObjectStore`
  slatedb/src/db/builder.rs
  slatedb/src/lib.rs
  slatedb/src/manifest/store.rs
  slatedb/src/retrying_object_store.rs
  slatedb/src/tablestore.rs
  slatedb/src/test_utils.rs
  slatedb/src/utils.rs
Labels: enhancement, size:L

#892 Expose errors' `ErrorKind`
  slatedb/src/error.rs
Labels: enhancement, size:XS

#888 Implement MessageHandler for CompactorEventHandler
  slatedb/src/compaction_execute_bench.rs
  slatedb/src/compactor.rs
  slatedb/src/compactor_executor.rs
  slatedb/src/db/builder.rs
  slatedb/src/dispatcher.rs
Labels: enhancement, size:L

#899 Add Windows support
  .github/workflows/pr.yaml
  Cargo.lock
  slatedb/Cargo.toml
  slatedb/benches/db_operations.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/test_utils.rs
Labels: enhancement, size:M

#873 feat(txn): and conflict check for SSI
  slatedb/src/batch_write.rs
  slatedb/src/transaction_manager.rs
Labels: enhancement, size:XL

#890 Implement MessageHandler for MemtableFlusher
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/utils.rs
Labels: enhancement, size:L

#891 Implement MessageHandler for WriteBatch
  slatedb/src/batch_write.rs
  slatedb/src/db.rs
  slatedb/src/db/builder.rs
Labels: enhancement, size:L

#902 Expose db builder through ffi, remove SlateDBOptions
  slatedb-go/README.md
  slatedb-go/go/batch_test.go
  slatedb-go/go/config.go
  slatedb-go/go/config_test.go
  slatedb-go/go/db.go
  slatedb-go/go/db_test.go
  slatedb-go/go/iterator_test.go
  slatedb-go/go/slatedb.h
  slatedb-go/src/config.rs
  slatedb-go/src/db.rs
  slatedb-go/src/db_reader.rs
  slatedb-go/src/object_store.rs
Labels: enhancement, size:XXL

#901 Expose fencing errors & mark `ErrorKind` as `non_exhaustive` and `Copy`
  slatedb/src/db.rs
  slatedb/src/error.rs
Labels: enhancement, size:S

#906 Fix `test_should_recover_imm_from_wal_after_flush_error`
  slatedb/src/batch_write.rs
  slatedb/src/checkpoint.rs
  slatedb/src/db.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/wal_buffer.rs
Labels: bug, size:M

#910 Add flaky test detection
  .github/workflows/nightly.yaml
Labels: enhancement, size:M

#914 Disable GH issue creation for nightly.yaml
  .github/workflows/nightly.yaml
Labels: maintenance, size:M

#911 wire in sequence tracker [RFC-0012]
  schemas/manifest.fbs
  slatedb-go/go/slatedb.h
  slatedb/src/batch_write.rs
  slatedb/src/compactor_state.rs
  slatedb/src/db.rs
  slatedb/src/db_reader.rs
  slatedb/src/db_state.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/generated/manifest_generated.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/oracle.rs
  slatedb/src/seq_tracker.rs
  slatedb/src/size_tiered_compaction.rs
  slatedb/src/wal_buffer.rs
Labels: enhancement, size:L

#909 Implement MessageHandler for DbReader
  slatedb/src/db_reader.rs
Labels: enhancement, size:L

#918 Replace `BackgroundTaskShutdown` with a clean shutdown
  slatedb/src/db.rs
  slatedb/src/dispatcher.rs
  slatedb/src/error.rs
  slatedb/src/garbage_collector.rs
  slatedb/src/mem_table_flush.rs
  slatedb/src/wal_buffer.rs
Labels: enhancement, size:M

#923 Wait for both writes in test_should_tombstones_in_l0
  slatedb/src/compactor.rs
  slatedb/src/db.rs
  slatedb/src/test_utils.rs
Labels: bug, size:M

#921 Don't double-cache object store in test helper
  slatedb/src/db.rs
Labels: bug, size:S

#893 Refactor manifest persistence to generic record primitives
  slatedb/src/error.rs
  slatedb/src/flatbuffer_types.rs
  slatedb/src/lib.rs
  slatedb/src/manifest/mod.rs
  slatedb/src/manifest/store.rs
  slatedb/src/record/mod.rs
  slatedb/src/record/store.rs
Labels: enhancement, maintenance, size:XXL
