Repository slatedb/slatedb, pull requests merged in 2025-03, with the labels that each got.

#496 write manifests more safely by verifying the expected next id
  src/checkpoint.rs
  src/clone.rs
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
  src/db_state.rs
  src/flush.rs
  src/garbage_collector.rs
  src/manifest/store.rs
  src/mem_table_flush.rs
  src/size_tiered_compaction.rs
Labels: enhancement, size:XL

#506 Make flush_interval optional (#505)
  src/checkpoint.rs
  src/compactor.rs
  src/config.rs
  src/db.rs
  src/flush.rs
Labels: enhancement, size:M

#507 Introduce SsTableHande::compacted_first_key to simplify handling of e…
  src/db.rs
  src/db_state.rs
  src/sorted_run_iterator.rs
Labels: enhancement, size:M

#500 Factor out WAL replay utility
  src/db.rs
  src/db_common.rs
  src/db_state.rs
  src/lib.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/wal_replay.rs
Labels: enhancement, size:XL

#501 Add ComparableRange module.
  src/comparable_range.rs
  src/lib.rs
Labels: enhancement, size:L

#474 Track all external DB references in the manifest
  schemas/manifest.fbs
  src/clone.rs
  src/db.rs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
  src/manifest/mod.rs
  src/manifest/store.rs
  src/paths.rs
  src/tablestore.rs
Labels: enhancement, size:XXL

#497 Replace `GetTarget` with `get_block`, `get_index`, and `get_filter` in `DbCache`
  src/db_cache/foyer.rs
  src/db_cache/mod.rs
  src/db_cache/moka.rs
  src/tablestore.rs
Labels: enhancement, size:L

#483 Update Checkpoints RFC: DbParent -> [ExternalDb].
  rfcs/0004-checkpoints.md
Labels: documentation, size:L

#498 Read only client implementation
  rfcs/0004-checkpoints.md
  src/config.rs
  src/db.rs
  src/db_reader.rs
  src/db_state.rs
  src/flush.rs
  src/lib.rs
  src/manifest/store.rs
  src/mem_table.rs
  src/reader.rs
  src/store_provider.rs
  src/tablestore.rs
  src/test_utils.rs
  src/types.rs
  src/utils.rs
  src/wal_replay.rs
Labels: enhancement, size:XXL

#440 docs: [RFC] Synchronous Commit & Durability
  rfcs/0007-synchronous-commit.md
Labels: documentation, size:L

#510 Add version bytes for SST and manifest byte formats
  src/error.rs
  src/flatbuffer_types.rs
  src/sst.rs
Labels: enhancement, size:L

#514 Add test case for db clone when source_checkpoint no longer exists.
  src/clone.rs
Labels: size:M

#515 Ran `cargo update` to pull in latest dependencies
  Cargo.lock
Labels: size:XS, dependencies

#518 fix: handle repeated keys during sst index search
  src/db.rs
  src/sst_iter.rs
Labels: bug, size:L

#522 fix block filtering when creating sst iterator
  src/flatbuffer_types.rs
  src/lib.rs
  src/partitioned_keyspace.rs
  src/sst_iter.rs
Labels: bug, size:L

#524 Add read/write integration test
  tests/db.rs
Labels: enhancement, size:L

#516 Reduce size of index blocks using lower bound index key
  src/sst.rs
  src/utils.rs
Labels: enhancement, size:L

#525 Add Serialize/Deserialize impls for CachedKey/CachedEntry
  Cargo.lock
  Cargo.toml
  src/block.rs
  src/db_cache/mod.rs
  src/db_cache/serde.rs
  src/flatbuffer_types.rs
Labels: enhancement, size:L

#526 add a dbcache impl that uses the foyer hybrid cache
  Cargo.lock
  Cargo.toml
  src/db_cache/foyer.rs
  src/db_cache/foyer_hybrid.rs
  src/db_cache/mod.rs
  src/db_cache/moka.rs
  src/error.rs
  src/tablestore.rs
Labels: enhancement, size:L

#529 change read level to durability filter
  src/config.rs
  src/db.rs
  src/db_reader.rs
  src/reader.rs
  src/utils.rs
Labels: enhancement, size:L
