Repository slatedb/slatedb, pull requests merged in 2025-01, with the labels that each got.

#425 Update `await` calls in README.md
  README.md
Labels: documentation, size:M

#427 chore: Apply table driven test for sst.rs
  src/sst.rs
Labels: maintenance, size:L

#429 fix: use milliseconds for the system clock
  src/config.rs
Labels: bug, size:XS

#426 Cleanup/simplify internal iterator usage
  src/block_iterator.rs
  src/bytes_range.rs
  src/compactor.rs
  src/compactor_executor.rs
  src/db.rs
  src/db_iter.rs
  src/db_state.rs
  src/proptest_util.rs
  src/sorted_run_iterator.rs
  src/sst.rs
  src/sst_iter.rs
  src/tablestore.rs
  src/test_utils.rs
Labels: maintenance, size:XXL

#435 Writer should merge added checkpoints into its db state
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
  src/db_state.rs
  src/mem_table_flush.rs
Labels: bug, size:M

#437 Compactor should account for checkpoints when merging manifest state
  src/compactor_state.rs
Labels: enhancement, size:M

#439 MINOR: reduce log level on clean shutdown and fix clippy warns
  src/batch_write.rs
  src/db_iter.rs
  src/mem_table.rs
  src/tablestore.rs
Labels: maintenance, size:S

#441 make metrics publicly visible
  src/lib.rs
Labels: enhancement, size:XS

#447 Freeze current memtable when flushing with wal disabled
  src/db.rs
Labels: enhancement, size:M

#448 Fix `wal_id_last_seen` race condition
  src/db.rs
  src/db_state.rs
  src/flush.rs
  src/mem_table.rs
Labels: bug, size:M

#432 fix issue with clock tick recovery reading from WAL
  schemas/manifest.fbs
  src/batch_write.rs
  src/compaction_execute_bench.rs
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/generated/manifest_generated.rs
  src/mem_table.rs
  src/mem_table_flush.rs
  src/size_tiered_compaction.rs
  src/utils.rs
Labels: bug, size:L

#391 2/N Merge Operator Iterator
  src/error.rs
  src/lib.rs
  src/merge_operator.rs
  src/types.rs
  src/utils.rs
Labels: enhancement, size:L

#443 Logic for creating checkpoints with control over scope
  rfcs/0004-checkpoints.md
  src/admin.rs
  src/checkpoint.rs
  src/cli/main.rs
  src/config.rs
  src/db.rs
  src/db_common.rs
  src/db_state.rs
  src/error.rs
  src/flush.rs
  src/manifest_store.rs
  src/mem_table_flush.rs
  src/test_utils.rs
Labels: enhancement, size:XL

#453 MINOR: Refactor wal flush msg for consistent pattern
  src/db.rs
  src/db_common.rs
  src/flush.rs
Labels: maintenance, size:M

#456 Consolidate checkpoint creation logic
  src/checkpoint.rs
  src/manifest_store.rs
  src/mem_table_flush.rs
Labels: enhancement, size:M

#457 Rename `bytes.rs` and re-export `bytes` crate
  src/bytes_generator.rs
  src/compaction_execute_bench.rs
  src/lib.rs
  src/sorted_run_iterator.rs
  src/sst_iter.rs
Labels: maintenance, size:S

#459 Fix implementation of defaults for user provided options. Implementat…
  src/compactor.rs
  src/config.rs
  src/db.rs
Labels: size:L

#450 Replace `&[u8]` with `AsRef<[u8]>` in public APIs
  README.md
  src/batch.rs
  src/bencher/db.rs
  src/db.rs
  src/db_iter.rs
  src/types.rs
Labels: enhancement, size:L

#444 make KeyValue visible so users of scan can access it
  src/lib.rs
  src/types.rs
Labels: enhancement, size:M

#461 Factor out path resolver
  src/garbage_collector.rs
  src/lib.rs
  src/paths.rs
  src/tablestore.rs
Labels: enhancement, size:L

#463 restructure exports to top level of crate
  benches/db_operations.rs
  src/batch.rs
  src/bencher/args.rs
  src/bencher/db.rs
  src/bencher/main.rs
  src/checkpoint.rs
  src/cli/main.rs
  src/config.rs
  src/db_cache/mod.rs
  src/error.rs
  src/lib.rs
  src/merge_operator.rs
  src/metrics.rs
Labels: enhancement, size:L

#468 Fix doc tests broken by pub use changes
  .github/workflows/pr.yaml
  README.md
  src/db.rs
  src/db_cache/foyer.rs
  src/db_cache/moka.rs
Labels: documentation, size:M

#469 Doc test all features
  .github/workflows/pr.yaml
Labels: documentation, size:XS

#389 feat(snapsot): add seq num to memtable
  .gitignore
  schemas/manifest.fbs
  src/batch_write.rs
  src/compactor.rs
  src/compactor_state.rs
  src/db.rs
  src/db_state.rs
  src/flatbuffer_types.rs
  src/flush.rs
  src/generated/manifest_generated.rs
  src/mem_table.rs
  src/merge_iterator.rs
  src/size_tiered_compaction.rs
  src/types.rs
Labels: enhancement, size:XXL

#430 Initial clone implementation
  rfcs/0004-checkpoints.md
  schemas/manifest.fbs
  src/admin.rs
  src/clone.rs
  src/db.rs
  src/db_state.rs
  src/error.rs
  src/flatbuffer_types.rs
  src/garbage_collector.rs
  src/generated/manifest_generated.rs
  src/lib.rs
  src/manifest.rs
  src/manifest_store.rs
  src/test_utils.rs
Labels: enhancement, size:XXL
